apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: guestbook
  name: guestbook-ui
  namespace: default
spec:
  type: LoadBalancer  # Change type to LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: guestbook-ui