apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 3
  # replicas: 1 # 1 porque é o highlander
  selector: 
    matchLabels: 
      app: nginx-simple
  template:
    metadata: 
      labels: 
        app: nginx-simple
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: curl
          image: curlimages/curl:8.8.0 # second container in the same pod
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting curl loop...";
              while true; do
                curl -s http://localhost:80 || echo "nginx not ready yet";
                sleep 5;
              done