apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}-files
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.files }}
  {{ $name }}: |
{{ $content | indent 4 }}
{{- end }}